classDiagram 
    class DataViewSchema {
      Count
      Item (index : int ) : DataViewSchema.Column
      Item (name : string)
    }
    class DataViewSchema_Builder {
      AddColumn()
      AddColumns()
      ToSchema() : DataViewSchema
    }
    class DataViewSchema_Column {
      Annotations
      Index
      IsHidden
      Name
      Type : DataViewType
      ToString() : string
    }
    class DataViewType {
      RawType : System.Type
    }
    class PrimitiveDataViewType 
    class KeyDataViewType
    class StructuredDataViewType
    class VectorDataViewType
    class TextDataViewType
    class NumberDataViewType
    class RowIdDataViewType
    class BooleanDataViewType
    class DateTimeDataViewType
    class DateTimeOffsetDataViewType
    class TimeSpanDataViewType
    class ImageDataViewType
    class OnnxSequenceType
    class OnnxMapType
    DataViewType <-- PrimitiveDataViewType
    PrimitiveDataViewType <-- KeyDataViewType
    PrimitiveDataViewType <-- TextDataViewType
    PrimitiveDataViewType <-- NumberDataViewType
    PrimitiveDataViewType <-- RowIdDataViewType
    PrimitiveDataViewType <-- BooleanDataViewType
    PrimitiveDataViewType <-- DateTimeDataViewType
    PrimitiveDataViewType <-- TimeSpanDataViewType
    PrimitiveDataViewType <-- DateTimeOffsetDataViewType
    DataViewType <-- StructuredDataViewType
    StructuredDataViewType <-- VectorDataViewType
    StructuredDataViewType <-- ImageDataViewType
    StructuredDataViewType <-- OnnxSequenceType
    StructuredDataViewType <-- OnnxMapType