classDiagram 
    class DataViewSchema {
      Count
      Item (index : int ) : DataViewSchema.Column
      Item (name : string)
    }
    class DataViewSchema_Builder {
      AddColumn()
      AddColumns()
      ToSchema() : DataViewSchema
    }
    class DataViewSchema_Column {
      Annotations
      Index
      IsHidden
      Name
      Type : DataViewType
      ToString() : string
    }
    class DataViewType {
      RawType : System.Type
    }
