classDiagram 
    class InternalRegressionTree {
        _maxOutput : double
        _previousLeafValue
        _splitGain : double[]
        GtChild
        LteChild
        MaxNumLeaves
        Thresholds
        Weights
        LeafValues
        ActiveFeatures
        CategoricalSplit
        CategoricalSplitFeatureRanges
        CategoricalSplitFeatures
        DefaultValueForMissing
        GainMap 
        GainPValues
        LeafValue()
        SumupValue()
        SizeInBytes()
        ShiftOutputs()
        UpdateOutputWithDelta()
        ToByteArray()
        ToOldIni()
    }