  sequenceDiagram 
    participant  SFPTB as  SingleFeaturePredictionTransformerBase
    participant  BM as  BindableMapper
    participant  SBPW as  SchemaBindablePredictorWrapper
      SFPTB->>BM: ScoreUtils.GetSchemaBindableMapper
      