 sequenceDiagram 
    participant  TB as  LightGBMTrainerBase
    participant  LGBMRegTrainerOpt as  LightGbmRegressionTrainerOptions
    participant  LGBMTrainerOpt as  LightGbmTrainerOptionsBase
    participant  BF as  BoosterFactory
    participant  BP as  BoosterParameterBase
    participant  BO as  BoosterOptions
      TB->>LGBMRegTrainerOpt: LightGbmTrainerOptions.ToDictionary()
      LGBMRegTrainerOpt->>LGBMTrainerOpt: (base) LightGbmTrainerOptions.ToDictionary()
      LGBMTrainerOpt->> BF: BoosterFactory.CreateComponent()
      LGBMTrainerOpt->> BP: UpdateParameters()
      BP->>BO: GetType().GetFields()