 sequenceDiagram 
    participant  TB as  LightGBMTrainerBase
    participant  LGBMTrainerOpt as  LightGbmTrainerOptions
    participant  BF as  BoosterFactory
    participant  BP as  BoosterParameterBase
    participant  BO as  BoosterOptions
      TB->>LGBMTrainerOpt: LightGbmTrainerOptions.ToDictionary()
      LGBMTrainerOpt->> BF: BoosterFactory.CreateComponent()
      LGBMTrainerOpt->> BP: UpdateParameters()
      BP->>BO: GetType().GetFields()