name: 'Compile Mermaid in Markdown'

on:
  push:
    paths:
      - '**/*.mmd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get Changed Files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.mmd$' | xargs)"

      - name: Print mmd Files Changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: Compile Mermaid Files
        uses: neenjaw/compile-mermaid-markdown-action@0.3.1
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'output'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"

      - name: Show Changes
        run: |
          git status

      # For manual inspection of the generated artifacts
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: output
          path: ./test-output
  